name: Fetch Gold Price

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı otomatik çalışır
  workflow_dispatch:     # Manuel tetikleme desteği

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run fetch-price script
        run: node fetch-price-and-set.js
